# Generated by Django 4.0.5 on 2022-06-07 12:56

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
    ]
