# Generated by Django 4.0.5 on 2022-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('pickup', 'PICKUP'), ('processing', 'PROCESSING'), ('delivered', 'DELIVERED')], max_length=200, null=True),
        ),
    ]
