# Generated by Django 4.0.5 on 2022-06-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_pickup_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pickup',
        ),
    ]
